### ISSUE TITLE
Duplicated error check condition on PriceOracle interaction layer

### ISSUE THREAD

**Issue by benjaminbollen** [ostdotcom/ost-price-oracle#40]
duplicated error code `l_ci_po_spd_3` is `l_ci_po_spd_5` "Zero Price is not allowed" https://github.com/OpenSTFoundation/ost-price-oracle/blob/master/lib/contract_interact/price_oracle.js#L145

**Comment by shlokgilda** [comment]
@benjaminbollen We can close this issue given the fact that the codebase has changed significantly since the issue was opened.
